#!/bin/sh
# vpn-dns-helper.sh
#
# One script for:
#  - OpenVPN: called via --up, uses foreign_option_* to set resolv.conf
#  - WireGuard / generic: called manually after wg-quick up, just tests DNS
#
# Safe to run multiple times; never exits non-zero on failure.

set -u

echo "[vpn-dns] Running DNS setup / test helper..."

# -------- 1) OpenVPN-specific: parse pushed DNS options, if present -------- #

# Detect if we're being called from OpenVPN (foreign_option_* env vars exist)
if env | grep -q '^foreign_option_1=' 2>/dev/null; then
    echo "[vpn-dns] Detected OpenVPN environment; parsing pushed DNS options"

    DNS_SERVERS=""
    i=1
    while :; do
        eval "opt=\${foreign_option_${i}:-}"
        [ -z "${opt}" ] && break

        case "$opt" in
            dhcp-option\ DNS\ *)
                # Example: 'dhcp-option DNS 10.211.254.254'
                dns_server=$(printf '%s\n' "$opt" | awk '{print $3}')
                DNS_SERVERS="$DNS_SERVERS $dns_server"
                ;;
        esac
        i=$((i+1))
    done

    if [ -n "$DNS_SERVERS" ]; then
        echo "[vpn-dns] Applying DNS servers from OpenVPN: $DNS_SERVERS"
        {
            echo "# Generated by vpn-dns-helper (OpenVPN pushed DNS)"
            for dns in $DNS_SERVERS; do
                echo "nameserver $dns"
            done
            echo "options edns0"
        } > /etc/resolv.conf
    else
        echo "[vpn-dns] No DNS servers pushed by OpenVPN; leaving /etc/resolv.conf as-is"
    fi
else
    echo "[vpn-dns] No OpenVPN foreign_option_* detected; assuming WireGuard or manual DNS"
    # Try to configure DNS from WireGuard (e.g., Mullvad) if available
    WG_CONF="${WG_CONF:-/etc/wireguard/wg0.conf}"

    if [ -f "$WG_CONF" ]; then
        # Look for a line like: DNS = 193.138.218.74, 185.213.154.36, 2a07:e340::2, 2a07:e340::3
        DNS_LINE=$(grep -E '^[[:space:]]*DNS[[:space:]]*=' "$WG_CONF" 2>/dev/null || true)

        if [ -n "$DNS_LINE" ]; then
            # Strip "DNS =" and spaces, turn commas into spaces
            DNS_SERVERS=$(printf '%s\n' "$DNS_LINE" \
                | cut -d'=' -f2 \
                | tr -d ' ' \
                | tr ',' ' ')

            if [ -n "$DNS_SERVERS" ]; then
                echo "[vpn-dns] Found DNS= in $WG_CONF: $DNS_SERVERS"
                echo "[vpn-dns] Overriding /etc/resolv.conf with WireGuard/Mullvad DNS"

                {
                    echo "# Generated by vpn-dns-helper.sh from $WG_CONF"
                    for s in $DNS_SERVERS; do
                        echo "nameserver $s"
                    done
                } > /etc/resolv.conf
            else
                echo "[vpn-dns] DNS= line in $WG_CONF is empty after parsing; leaving resolv.conf unchanged"
            fi
        else
            echo "[vpn-dns] No DNS= line found in $WG_CONF; leaving resolv.conf unchanged"
        fi
    else
        echo "[vpn-dns] WireGuard config $WG_CONF not found; leaving resolv.conf unchanged"
    fi
fi

# -------- 2) Show current DNS configuration -------- #

echo "[vpn-dns] Current /etc/resolv.conf:"
if [ -f /etc/resolv.conf ]; then
    sed 's/^/[vpn-dns]   /' /etc/resolv.conf
else
    echo "[vpn-dns]   (no resolv.conf found)"
fi

# -------- 3) DNS reachability test (works for both OpenVPN & WireGuard) -------- #

TEST_HOST="${VPN_DNS_TEST_HOST:-www.google.com}"

echo "[vpn-dns] Testing DNS resolution for ${TEST_HOST} (A/AAAA)"
TMP_OUT="/tmp/vpn-dns-test.$$"

if getent ahosts "$TEST_HOST" >"$TMP_OUT" 2>&1; then
    echo "[vpn-dns] DNS test SUCCESS:"
    sed 's/^/[vpn-dns]   /' "$TMP_OUT"
else
    echo "[vpn-dns] DNS test FAILED; getent output:"
    sed 's/^/[vpn-dns]   /' "$TMP_OUT" 2>/dev/null || true
fi

rm -f "$TMP_OUT" 2>/dev/null || true

exit 0
