#!/bin/sh
# vpn-dns-helper.sh
#
# One script for:
#  - OpenVPN: called via --up, uses foreign_option_* to set resolv.conf
#  - WireGuard / generic: called manually after wg-quick up, just tests DNS
#
# Safe to run multiple times; never exits non-zero on failure.

set -u

echo "[vpn-dns] Running DNS setup / test helper..."

# -------- 1) OpenVPN-specific: parse pushed DNS options, if present -------- #

# Detect if we're being called from OpenVPN (foreign_option_* env vars exist)
if env | grep -q '^foreign_option_1=' 2>/dev/null; then
    echo "[vpn-dns] Detected OpenVPN environment; parsing pushed DNS options"

    DNS_SERVERS=""
    i=1
    while :; do
        eval "opt=\${foreign_option_${i}:-}"
        [ -z "${opt}" ] && break

        case "$opt" in
            dhcp-option\ DNS\ *)
                # Example: 'dhcp-option DNS 10.211.254.254'
                dns_server=$(printf '%s\n' "$opt" | awk '{print $3}')
                DNS_SERVERS="$DNS_SERVERS $dns_server"
                ;;
        esac
        i=$((i+1))
    done

    if [ -n "$DNS_SERVERS" ]; then
        echo "[vpn-dns] Applying DNS servers from OpenVPN: $DNS_SERVERS"
        {
            echo "# Generated by vpn-dns-helper (OpenVPN pushed DNS)"
            for dns in $DNS_SERVERS; do
                echo "nameserver $dns"
            done
            echo "options edns0"
        } > /etc/resolv.conf
    else
        echo "[vpn-dns] No DNS servers pushed by OpenVPN; leaving /etc/resolv.conf as-is"
    fi
else
    echo "[vpn-dns] No OpenVPN foreign_option_* detected; assuming WireGuard or manual DNS"
fi

# -------- 2) Show current DNS configuration -------- #

echo "[vpn-dns] Current /etc/resolv.conf:"
if [ -f /etc/resolv.conf ]; then
    sed 's/^/[vpn-dns]   /' /etc/resolv.conf
else
    echo "[vpn-dns]   (no resolv.conf found)"
fi

# -------- 3) DNS reachability test (works for both OpenVPN & WireGuard) -------- #

TEST_HOST="${VPN_DNS_TEST_HOST:-www.google.com}"

echo "[vpn-dns] Testing DNS resolution for ${TEST_HOST} (A/AAAA)"
TMP_OUT="/tmp/vpn-dns-test.$$"

if getent ahosts "$TEST_HOST" >"$TMP_OUT" 2>&1; then
    echo "[vpn-dns] DNS test SUCCESS:"
    sed 's/^/[vpn-dns]   /' "$TMP_OUT"
else
    echo "[vpn-dns] DNS test FAILED; getent output:"
    sed 's/^/[vpn-dns]   /' "$TMP_OUT" 2>/dev/null || true
fi

rm -f "$TMP_OUT" 2>/dev/null || true

exit 0
